name: 'Format and Lint'
on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v6

      - name: 'Setup tools and dependencies'
        uses: ./.github/actions/setup-tools

      - name: 'Check formatting'
        if: always()
        run: npm run format

      - name: 'Check lint'
        if: always()
        run: npm run lint
