name: 'Format and Lint'
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v6.0.3

      - name: 'Detect relevant changes'
        id: changes
        uses: ./.github/actions/detect-relevant-changes

      - name: 'Setup tools and dependencies'
        if: steps.changes.outputs.relevant == 'true'
        uses: ./.github/actions/setup-tools

      - name: 'Check formatting'
        if: always() && steps.changes.outputs.relevant == 'true'
        run: pnpm run format

      - name: 'Check lint'
        if: always() && steps.changes.outputs.relevant == 'true'
        run: pnpm run lint
